set_property IOSTANDARD LVCMOS33 [get_ports bu]

set_property PACKAGE_PIN H17 [get_ports bu]


set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]


set_property PACKAGE_PIN F5 [get_ports {vga_rgb[11]}]
set_property PACKAGE_PIN C6 [get_ports {vga_rgb[10]}]
set_property PACKAGE_PIN C5 [get_ports {vga_rgb[9]}]
set_property PACKAGE_PIN B7 [get_ports {vga_rgb[8]}]
set_property PACKAGE_PIN B6 [get_ports {vga_rgb[7]}]
set_property PACKAGE_PIN A6 [get_ports {vga_rgb[6]}]
set_property PACKAGE_PIN A5 [get_ports {vga_rgb[5]}]
set_property PACKAGE_PIN D8 [get_ports {vga_rgb[4]}]
set_property PACKAGE_PIN C7 [get_ports {vga_rgb[3]}]
set_property PACKAGE_PIN E6 [get_ports {vga_rgb[2]}]
set_property PACKAGE_PIN E5 [get_ports {vga_rgb[1]}]
set_property PACKAGE_PIN E7 [get_ports {vga_rgb[0]}]
set_property PACKAGE_PIN D7 [get_ports hsync]
set_property PACKAGE_PIN C4 [get_ports vsync]



set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rst_de]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports thr]
set_property IOSTANDARD LVCMOS33 [get_ports bra]
set_property IOSTANDARD LVCMOS33 [get_ports clu]
set_property IOSTANDARD LVCMOS33 [get_ports rgs]
set_property IOSTANDARD LVCMOS33 [get_ports test]
set_property IOSTANDARD LVCMOS33 [get_ports turn_left]
set_property IOSTANDARD LVCMOS33 [get_ports turn_right]

set_property PACKAGE_PIN N5 [get_ports rx]
set_property PACKAGE_PIN P17 [get_ports sys_clk]
set_property PACKAGE_PIN R15 [get_ports rst_de]
set_property PACKAGE_PIN T4 [get_ports tx]
set_property PACKAGE_PIN P5 [get_ports thr]
set_property PACKAGE_PIN P4 [get_ports bra]
set_property PACKAGE_PIN P3 [get_ports clu]
set_property PACKAGE_PIN P2 [get_ports rgs]
set_property PACKAGE_PIN K3 [get_ports test]
set_property PACKAGE_PIN K1 [get_ports turn_left]
set_property PACKAGE_PIN H6 [get_ports turn_right]


set_property PACKAGE_PIN H4 [get_ports front_detector]
set_property PACKAGE_PIN J2 [get_ports left_detector]
set_property PACKAGE_PIN K2 [get_ports right_detector]
set_property PACKAGE_PIN J3 [get_ports back_detector]
set_property PACKAGE_PIN V1 [get_ports turn_left_signal]
set_property PACKAGE_PIN R11 [get_ports turn_right_signal]
set_property IOSTANDARD LVCMOS33 [get_ports turn_left_signal]
set_property IOSTANDARD LVCMOS33 [get_ports turn_right_signal]
set_property IOSTANDARD LVCMOS33 [get_ports back_detector]
set_property IOSTANDARD LVCMOS33 [get_ports front_detector]
set_property IOSTANDARD LVCMOS33 [get_ports left_detector]
set_property IOSTANDARD LVCMOS33 [get_ports right_detector]


set_property PACKAGE_PIN U4 [get_ports move_forward_signal]
set_property IOSTANDARD LVCMOS33 [get_ports move_forward_signal]

set_property PACKAGE_PIN R17 [get_ports move_backward_signal]
set_property IOSTANDARD LVCMOS33 [get_ports move_backward_signal]


set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg1_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {swi[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swi[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swi[0]}]
set_property PACKAGE_PIN M4 [get_ports {swi[2]}]
set_property PACKAGE_PIN N4 [get_ports {swi[1]}]
set_property PACKAGE_PIN R1 [get_ports {swi[0]}]

set_property PACKAGE_PIN G2 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN C2 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN C1 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN H1 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN G1 [get_ports {seg1_en[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg1_en[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg1_en[1]}]
set_property PACKAGE_PIN G6 [get_ports {seg1_en[0]}]

set_property PACKAGE_PIN B4 [get_ports {seg_out[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_out[0]}]


set_property PACKAGE_PIN D4 [get_ports {seg1_out[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg1_out[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg1_out[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg1_out[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg1_out[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg1_out[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg1_out[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg1_out[0]}]


